# pathwar/node:0.10.34 pathwar/node:0.10 pathwar/node:0 pathwar/node:latest
FROM node:0.10.34
MAINTAINER Pathwar Team <team@pathwar.net> (@pathwar_net)

# Install dependencies
#RUN apt-get update \
# && apt-get -y -q upgrade \
# && apt-get -y -q install curl \
# && apt-get clean

# Add Pathwar tools
COPY skeleton /pathwar
