base_url: "https://pathwar.crowdin.com"
commit_message: 'chore(i18n): new %language% translations


Signed-off-by: Pathwar Bot <11067407+pathwar-bot@users.noreply.github.com>
'

append_commit_message: false
preserve_hierarchy: true

files:
  - source: /web/src/translations/en.json
    translation: /web/src/translations/%two_letters_code%.json
  - source: /challenges/web/upload-hi/front/translations/en_US/LC_MESSAGES/*.po
    translation: /challenges/web/upload-hi/front/translations/%locale_with_underscore%/LC_MESSAGES/%original_file_name%
