project_id: '2'
base_url: 'https://pathwar.crowdin.com'
commit_message: |-
  chore(i18n): new %language% translations

append_commit_message: false
preserve_hierarchy: true
files:
  - source: /web/src/translations/en.json
    translation: /web/src/translations/%two_letters_code%.json
  - source: /challenges/web/upload-hi/front/translations/en_US/LC_MESSAGES/*.po
    translation: /challenges/web/upload-hi/front/translations/%locale_with_underscore%/LC_MESSAGES/%original_file_name%
  - source: /challenges/web/training-sqli/front/translations/en_US/LC_MESSAGES/*.po
    translation: /challenges/web/training-sqli/front/translations/%locale_with_underscore%/LC_MESSAGES/%original_file_name%
  - source: /challenges/web/training-include/front/translations/en_US/LC_MESSAGES/*.po
    translation: /challenges/web/training-include/front/translations/%locale_with_underscore%/LC_MESSAGES/%original_file_name%
