# builder
FROM            golang:1.17-alpine as builder
RUN             apk --no-cache --update add npm make gcc g++ musl-dev openssl-dev git perl-utils
WORKDIR         /go/src/pathwar.land
ENV             GO111MODULE=on GOPROXY=https://proxy.golang.org,direct
COPY            go.mod go.sum ./
RUN             go mod download
RUN             go get github.com/gobuffalo/packr/v2/packr2
COPY            . .
WORKDIR         /go/src/pathwar.land/go
RUN             make packr
RUN             make install

# runtime
FROM devago/docker-compose
COPY --from=builder /go/bin/pathwar /bin/
ENTRYPOINT ["/bin/pathwar"]
