#!/bin/sh

printf '/--------------------------------------------------------\\\n'
printf '|     Welcome on %-36s    |\n' $(hostname)'!'
printf '\\--------------------------------------------------------/\n'

cat <<EOF

Useful commands installed:
  - gdb, ltrace, strace, nm, objdump, ldd, hexdump
  - gcc, php, perl, python, ruby
  - wget, curl, socat, nc, tcpdump, nmap
  - emacs, vim, mg
EOF
