#!/bin/sh

FILE=~bobby/level

echo
if [ -x ~$FILE ]; then
    printf '/--------------------------------------------------------\\\n'
    printf '|     Challenge %42s        |\n' $FILE
    printf '\\--------------------------------------------------------/\n'
    echo
    file $(readlink -f $FILE)
    echo
fi
