#!/bin/sh

FILE=~bobby/level

echo
if [ -f $(readlink -f $FILE) ]; then
    printf '/--------------------------------------------------------\\\n'
    printf '|     Challenge %-36s     |\n' $FILE
    printf '\\--------------------------------------------------------/\n'
    echo
    file $(readlink -f $FILE)
    echo
fi
