
//Login / Session
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SET_USER_SESSION = "SET_USER_SESSION";
export const SET_USER_SESSION_FAILED = "SET_USER_SESSION_FAILED";
export const SET_KEYCLOAK_SESSION = "SET_KEYCLOAK_SESSION";
export const LOGOUT = "LOGOUT";

//Teams
export const SET_ACTIVE_TEAM = "SET_ACTIVE_TEAM";
export const GET_USER_TEAMS = "GET_USER_TEAMS";
export const GET_USER_TEAMS_SUCCESS = "GET_USER_TEAMS_SUCCESS";
export const GET_USER_TEAMS_FAILED = "GET_USER_TEAMS_FAILED";
export const SET_TEAMS_LIST = "SET_TEAMS_LIST";
export const SET_TEAMS_LIST_FAILED = "SET_TEAMS_LIST_FAILED";
export const JOIN_TEAM_SUCCESS = "JOIN_TEAM_SUCCESS";
export const JOIN_TEAM_FAILED = "JOIN_TEAM_FAILED";
export const GET_TEAM_DETAILS_SUCCESS = "GET_TEAM_DETAILS_SUCCESS";
export const GET_TEAM_DETAILS_FAILED = "GET_TEAM_DETAILS_FAILED";

//Season
export const GET_ALL_SEASONS_SUCCESS = "GET_ALL_SEASONS_SUCCESS";
export const GET_ALL_SEASONS_FAILED = "GET_ALL_SEASONS_FAILED";
export const SET_ACTIVE_SEASON = "SET_ACTIVE_SEASON";
export const SET_ACTIVE_SEASON_FAILED = "SET_ACTIVE_SEASON_FAILED";
export const SET_CHALLENGES_LIST = "SET_CHALLENGES_LIST";
export const SET_CHALLENGES_LIST_FAILED = "SET_CHALLENGES_LIST_FAILED";
export const SET_DEFAULT_SEASON = "SET_DEFAULT_SEASON";
export const FETCH_PREFERENCES_SUCCESS = "FETCH_PREFERENCES_SUCCESS";
export const FETCH_PREFERENCES_FAILED = "FETCH_PREFERENCES_FAILED";
export const GET_ALL_SEASON_TEAMS_SUCCESS = "GET_ALL_SEASON_TEAMS_SUCCESS";
export const GET_ALL_SEASON_TEAMS_FAILED = "GET_ALL_SEASON_TEAMS_FAILED";
export const GET_CHALLENGE_DETAILS_SUCCESS = "GET_CHALLENGE_DETAILS_SUCCESS";
export const GET_CHALLENGE_DETAILS_FAILED = "GET_CHALLENGE_DETAILS_FAILED";
