//Login / Session
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SET_USER_SESSION = "SET_USER_SESSION";
export const SET_USER_SESSION_FAILED = "SET_USER_SESSION_FAILED";
export const SET_KEYCLOAK_SESSION = "SET_KEYCLOAK_SESSION";
export const LOGOUT = "LOGOUT";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAILED = "DELETE_ACCOUNT_FAILED";

//ORganizations
export const SET_ACTIVE_ORGANIZATION = "SET_ACTIVE_ORGANIZATION";
export const SET_ORGANIZATIONS_LIST = "SET_ORGANIZATIONS_LIST";
export const SET_ORGANIZATIONS_LIST_FAILED = "SET_ORGANIZATIONS_LIST_FAILED";
export const SET_USER_ORGANIZATIONS_LIST = "SET_USER_ORGANIZATIONS_LIST";
export const GET_ORGANIZATION_DETAILS_SUCCESS = "GET_ORGANIZATION_DETAILS_SUCCESS";
export const GET_ORGANIZATION_DETAILS_FAILED = "GET_ORGANIZATION_DETAILS_FAILED";
export const CLEAN_ORGANIZATION_DETAILS = "CLEAN_ORGANIZATION_DETAILS";
export const INVITE_USER_TO_ORGANIZATION_SUCCESS = "INVITE_USER_TO_ORGANIZATION_SUCCESS";
export const INVITE_USER_TO_ORGANIZATION_FAILED = "INVITE_USER_TO_ORGANIZATION_FAILED";
export const LIST_USER_ORGANIZATIONS_INVITATIONS_SUCCESS = "LIST_USER_ORGANIZATIONS_INVITATIONS_SUCCESS";
export const LIST_USER_ORGANIZATIONS_INVITATIONS_FAILED = "LIST_USER_ORGANIZATIONS_INVITATIONS_FAILED";

//Season
export const GET_ALL_SEASONS_SUCCESS = "GET_ALL_SEASONS_SUCCESS";
export const GET_ALL_SEASONS_FAILED = "GET_ALL_SEASONS_FAILED";
export const SET_ACTIVE_SEASON = "SET_ACTIVE_SEASON";
export const SET_ACTIVE_SEASON_FAILED = "SET_ACTIVE_SEASON_FAILED";
export const SWITCH_SEASON = "SWITCH_SEASON";
export const SWITCH_SEASON_FAILED = "SWITCH_SEASON_FAILED";

export const SET_CHALLENGES_LIST = "SET_CHALLENGES_LIST";
export const SET_CHALLENGES_LIST_FAILED = "SET_CHALLENGES_LIST_FAILED";

export const FETCH_PREFERENCES_SUCCESS = "FETCH_PREFERENCES_SUCCESS";
export const FETCH_PREFERENCES_FAILED = "FETCH_PREFERENCES_FAILED";
export const GET_ALL_SEASON_TEAMS_SUCCESS = "GET_ALL_SEASON_TEAMS_SUCCESS";
export const GET_ALL_SEASON_TEAMS_FAILED = "GET_ALL_SEASON_TEAMS_FAILED";

export const GET_CHALLENGE_DETAILS_SUCCESS = "GET_CHALLENGE_DETAILS_SUCCESS";
export const GET_CHALLENGE_DETAILS_FAILED = "GET_CHALLENGE_DETAILS_FAILED";
export const CLEAN_CHALLENGE_DETAIL = "CLEAN_CHALLENGE_DETAIL";

export const GET_TEAM_DETAILS_SUCCESS = "GET_TEAM_DETAILS_SUCCESS";
export const GET_TEAM_DETAILS_FAILED = "GET_TEAM_DETAILS_FAILED";

export const BUY_CHALLENGE_SUCCESS = "BUY_CHALLENGE_SUCCESS";
export const BUY_CHALLENGE_FAILED = "BUY_CHALLENGE_FAILED";
export const VALIDATE_CHALLENGE_SUCCESS = "VALIDATE_CHALLENGE_SUCCESS";
export const VALIDATE_CHALLENGE_FAILED = "VALIDATE_CHALLENGE_FAILED";
export const CLOSE_CHALLENGE_SUCCESS = "CLOSE_CHALLENGE_SUCCESS";
export const CLOSE_CHALLENGE_FAILED = "CLOSE_CHALLENGE_FAILED";

export const SET_ACTIVE_TEAM = "SET_ACTIVE_TEAM";
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const CREATE_TEAM_FAILED = "CREATE_TEAM_FAILED";

export const VALIDATE_COUPON_SUCCESS = "VALIDATE_COUPON_SUCCESS";
export const VALIDATE_COUPON_FAILED = "VALIDATE_COUPON_FAILED";
