
//Login / Session
export const PERFORM_LOGIN = "PERFORM_LOGIN";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SET_USER_SESSION = "SET_USER_SESSION";
export const PING_USER_SUCCESS = "PING_USER_SUCCESS";
export const PING_USER_FAILED = "PING_USER_FAILED";

//Teams
export const GET_USER_TEAMS = "GET_USER_TEAMS";
export const GET_USER_TEAMS_SUCCESS = "GET_USER_TEAMS_SUCCESS";
export const GET_USER_TEAMS_FAILED = "GET_USER_TEAMS_FAILED";
export const SET_TEAMS_LIST = "SET_TEAMS_LIST";
export const SET_TEAMS_LIST_FAILED = "SET_TEAMS_LIST_FAILED";

//Levels
export const GET_USER_COMPETITIONS = "GET_USER_COMPETITIONS";
export const GET_USER_COMPETITIONS_SUCCESS = "GET_USER_COMPETITIONS_SUCCESS";
export const GET_USER_COMPETITIONS_FAILED = "GET_USER_COMPETITIONS_FAILED";
export const SET_ACTIVE_COMPETITION = "SET_ACTIVE_COMPETITION";
export const SET_LEVELS_LIST = "SET_LEVELS_LIST";
export const SET_LEVELS_LIST_FAILED = "SET_LEVELS_LIST_FAILED";
