# -*- coding: utf-8 -*-

import random
import urllib

from flask import current_app


def check_request_item(request, item):
    if not item:
        abort(422, 'Invalid data')


def field_changed(field, payload, original):
    if field not in payload:
        return False

    if not field in original:
        return True

    return payload[field] != original[field]


def request_get_user(request):
    auth = request.authorization
    if auth.get('username'):
        if auth.get('password'):  # user:pass
            username = auth.get('username')
            try:
                username = urllib.unquote(username)
            except:
                pass
            return current_app.data.driver.db['raw-users'].find_one({
                '$or': [
                    {'login': username},
                    {'email': username},
                ]
                # 'active': True,  # FIXME: Reenable later
            })
        else:  # token
            user_token = current_app \
                .data \
                .driver \
                .db['raw-user-tokens'] \
                .find_one({
                    'token': auth.get('username')
                })
            if user_token:
                return current_app \
                    .data \
                    .driver \
                    .db['raw-users'] \
                    .find_one({'_id': user_token['user']})
    return None


def is_restricted_word(input_):
    input_ = input_.lower()

    restricted_words = (
        'supportdetails',
        'support-details',
        'stacks',
        'imulus',
        'github',
        'twitter',
        'facebook',
        'google',
        'apple',
        'about',
        'account',
        'activate',
        'add',
        'admin',
        'administrator',
        'api',
        'app',
        'apps',
        'archive',
        'archives',
        'auth',
        'blog',
        'cache',
        'cancel',
        'careers',
        'cart',
        'changelog',
        'checkout',
        'codereview',
        'compare',
        'config',
        'configuration',
        'connect',
        'contact',
        'create',
        'delete',
        'direct_messages',
        'documentation',
        'download',
        'downloads',
        'edit',
        'email',
        'employment',
        'enterprise',
        'faq',
        'favorites',
        'feed',
        'feedback',
        'feeds',
        'fleet',
        'fleets',
        'follow',
        'followers',
        'following',
        'friend',
        'friends',
        'gist',
        'group',
        'groups',
        'help',
        'home',
        'hosting',
        'hostmaster',
        'idea',
        'ideas',
        'index',
        'info',
        'invitations',
        'invite',
        'is',
        'it',
        'job',
        'jobs',
        'json',
        'language',
        'languages',
        'lists',
        'login',
        'logout',
        'logs',
        'mail',
        'map',
        'maps',
        'mine',
        'mis',
        'news',
        'oauth',
        'oauth_clients',
        'offers',
        'openid',
        'order',
        'orders',
        'organizations',
        'plans',
        'popular',
        'post',
        'postmaster',
        'privacy',
        'projects',
        'put',
        'recruitment',
        'register',
        'remove',
        'replies',
        'root',
        'rss',
        'sales',
        'save',
        'search',
        'security',
        'sessions',
        'settings',
        'shop',
        'signup',
        'sitemap',
        'ssl',
        'ssladmin',
        'ssladministrator',
        'sslwebmaster',
        'status',
        'stories',
        'styleguide',
        'subscribe',
        'subscriptions',
        'support',
        'sysadmin',
        'sysadministrator',
        'terms',
        'tour',
        'translations',
        'trends',
        'unfollow',
        'unsubscribe',
        'update',
        'url',
        'user',
        'weather',
        'webmaster',
        'widget',
        'widgets',
        'wiki',
        'ww',
        'www',
        'wwww',
        'xfn',
        'xml',
        'xmpp',
        'yaml',
        'yml',
        'chinese',
        'mandarin',
        'spanish',
        'english',
        'bengali',
        'hindi',
        'portuguese',
        'russian',
        'japanese',
        'german',
        'wu',
        'javanese',
        'korean',
        'french',
        'vietnamese',
        'telugu',
        'chinese',
        'marathi',
        'tamil',
        'turkish',
        'urdu',
        'min-nan',
        'jinyu',
        'gujarati',
        'polish',
        'arabic',
        'ukrainian',
        'italian',
        'xiang',
        'malayalam',
        'hakka',
        'kannada',
        'oriya',
        'panjabi',
        'sunda',
        'panjabi',
        'romanian',
        'bhojpuri',
        'azerbaijani',
        'farsi',
        'maithili',
        'hausa',
        'arabic',
        'burmese',
        'serbo-croatian',
        'gan',
        'awadhi',
        'thai',
        'dutch',
        'yoruba',
        'sindhi',
    )
    return input_ in restricted_words


def generate_name(sep='-'):
    """ Python port of github.com/docker/docker names-generator.go
    """
    left = [
        "admiring",
        "adoring",
        "agitated",
        "angry",
        "backstabbing",
        "berserk",
        "boring",
        "clever",
        "cocky",
        "compassionate",
        "condescending",
        "cranky",
        "desperate",
        "determined",
        "distracted",
        "dreamy",
        "drunk",
        "ecstatic",
        "elated",
        "elegant",
        "evil",
        "fervent",
        "focused",
        "furious",
        "gloomy",
        "goofy",
        "grave",
        "happy",
        "high",
        "hopeful",
        "hungry",
        "insane",
        "jolly",
        "jovial",
        "kickass",
        "lonely",
        "loving",
        "mad",
        "modest",
        "naughty",
        "nostalgic",
        "pensive",
        "prickly",
        "reverent",
        "romantic",
        "sad",
        "serene",
        "sharp",
        "sick",
        "silly",
        "sleepy",
        "stoic",
        "stupefied",
        "suspicious",
        "tender",
        "thirsty",
        "trusting",
    ]
    right = [
        "albattani",
        "almeida",
        "archimedes",
        "ardinghelli",
        "babbage",
        "banach",
        "bardeen",
        "brattain",
        "shockley",
        "bartik",
        "bell",
        "blackwell",
        "bohr",
        "brown",
        "carson",
        "colden",
        "cori",
        "cray",
        "curie",
        "darwin",
        "davinci",
        "einstein",
        "elion",
        "engelbart",
        "euclid",
        "fermat",
        "fermi",
        "feynman",
        "franklin",
        "galileo",
        "goldstine",
        "goodall",
        "hawking",
        "heisenberg",
        "hodgkin",
        "hoover",
        "hopper",
        "hypatia",
        "jang",
        "jones",
        "kilby",
        "noyce",
        "kirch",
        "kowalevski",
        "lalande",
        "leakey",
        "lovelace",
        "lumiere",
        "mayer",
        "mccarthy",
        "mcclintock",
        "mclean",
        "meitner",
        "mestorf",
        "morse",
        "newton",
        "nobel",
        "payne",
        "pare",
        "pasteur",
        "perlman",
        "pike",
        "poincare",
        "poitras",
        "ptolemy",
        "ritchie",
        "thompson",
        "rosalind",
        "sammet",
        "sinoussi",
        "stallman",
        "swartz",
        "tesla",
        "torvalds",
        "turing",
        "wilson",
        "wozniak",
        "wright",
        "yalow",
        "yonath",
    ]
    return random.choice(left) + sep + random.choice(right)


def check_blacklisted_email(email):
    domain = email.split('@')[1]
    blacklisted_domains = [
        '0815.ru',
        '10x9.com',
        '12minutemail.com',
        '1800newcareer.co.cc',
        '1chuan.com',
        '1zhuan.com',
        '4warding.com',
        '4warding.net',
        '4warding.org',
        '5ymail.com',
        'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk.com',
        'advantimo.com',
        'agedmail.com',
        'amail4.me',
        'ano-mail.net',
        'anobox.ru',
        'anonymbox.com',
        'asdasd.ru',
        'b.pythonboard.de',
        'brennendesreich.de',
        'buffemail.com',
        'bugmenot.com',
        'bund.us',
        'bx.mintemail.com',
        'cool.fr.nf',
        'courriel.fr.nf',
        'cust.in',
        'dbunker.com',
        'deadaddress.com',
        'despammed.com',
        'dingbone.com',
        'discardmail.com',
        'discardmail.de',
        'disposableinbox.com',
        'dispostable.com',
        'dontreg.com',
        'drdrb.com',
        'duskmail.com',
        'e4ward.com',
        'easy-trash-mail.com',
        'easytrashmail.com',
        'email-jetable.biz.st',
        'email-jetable.fr',
        'email-jetable.me',
        'emailias.com',
        'emaillime.com',
        'etsnt.co.uk',
        'fakebox.org',
        'fakedemail.com',
        'fakemailz.com',
        'filzmail.com',
        'flurred.com',
        'flyspam.com',
        'freemail.ms',
        'fudgerub.com',
        'gaudiumetspes.happyforever.com',
        'get2mail.fr',
        'gishpuppy.com',
        'grr.la',
        'guerrillamail.biz',
        'guerrillamail.com',
        'guerrillamail.de',
        'guerrillamail.net',
        'guerrillamail.org',
        'guerrillamailblock.com',
        'harvard.edu.tr.vu',
        'hidemail.de',
        'hmamail.com',
        'hulapla.de',
        'imstations.com',
        'incognitomail.com',
        'incognitomail.org',
        'jetable.fr.nf',
        'jetable.org',
        'kasmail.com',
        'koszmail.pl',
        'kurzepost.de',
        'lookugly.com',
        'lowiq.linux-board.com',
        'mail-temporaire.com',
        'mail-temporaire.fr',
        'mailHazard.com',
        'mailHazard.us',
        'mailHz.me',
        'mailcatch.com',
        'mailcatch.legendoftavlon.com',
        'mailcatch.loveafraid.com.ar',
        'maileater.com',
        'mailexpire.com',
        'mailforspam.com',
        'mailfreeonline.com',
        'mailinator.com',
        'mailincubator.com',
        'mailmetrash.com',
        'mailmoat.com',
        'mailnesia.com',
        'mailnull.com',
        'mailshell.com',
        'mailspeed.ru',
        'mailsto.co.cc',
        'mailtemporaire.com',
        'mailtemporaire.fr',
        'mailzilla.com',
        'mega.zik.dj',
        'meltmail',
        'meltmail.com',
        'mfsa.ru',
        'mintemail.com',
        'moncourrier.fr.nf',
        'monemail.fr.nf',
        'monmail.fr.nf',
        'mt2009.com',
        'mt2014.com',
        'mytempemail.com',
        'mytrashmail.com',
        'netzidiot.de',
        'no-spam.ws',
        'nomail.xl.cx',
        'nospam.ze.tc',
        'objectmail.com',
        'opayq.com',
        'proxymail.eu',
        'punkass.com',
        'rcpt.at',
        'reallymymail.com',
        'reply.li',
        'rmqkr.net',
        'rockuniverze.co.cc',
        's0ny.net',
        'safersignup.de',
        'sharklasers.com',
        'shiftmail.com',
        'shitmail.me',
        'smellfear.com',
        'sneakemail.com',
        'sofimail.com',
        'spam.la',
        'spam.su',
        'spam4.me',
        'spamavert.com',
        'spambob.net',
        'spambog.com',
        'spambog.de',
        'spambog.ru',
        'spambox.us',
        'spamex.com',
        'spamfree24.org',
        'spamgourmet.com',
        'spamhole.com',
        'spammotel.com',
        'spamobox.com',
        'spamslicer.com',
        'spamtrail.com',
        'speed.1s.fr',
        'superstachel.de',
        'teewars.org',
        'tempemail.net',
        'tempinbox.com',
        'temporaryforwarding.com',
        'thankyou2010.com',
        'thismail.ru',
        'trash-mail.at',
        'trash2009.com',
        'trashcanmail.com',
        'trashmail.at',
        'trashmail.me',
        'trashmail.net',
        'trashymail.com',
        'trbvm.com',
        'unmail.ru',
        'uroid.com',
        'wegwerfmail.de',
        'wegwerfmail.net',
        'wegwerfmail.org',
        'wh4f.org',
        'whatpaas.com',
        'xemaps.com',
        'xmaily.com',
        'yopmail.com',
        'yopmail.fr',
        'yopmail.net',
        'you.e4ward.com',
        'ypmail.webarnak.fr.eu.org',
        'zebins.com',
        'zebins.eu',
    ]
    return domain in blacklisted_domains
