version: '3.7'

# releases metadata (optional)
x-pathwar:
  challenge:
    name: "The magic number is 64"
    slug: base64encoding
    locale: "en"
    author: "Undercover L3mons"
    homepage: https://github.com/pathwar/pathwar/tree/master/challenges/crypto/base64encoding
  flavor:
    purchase_price: 0
    validation_reward: 1
    body: |
      Introduction to crypto challenges.

      "I don't know how to decode this."
    passphrases: 1
    category: crypto
    tags:
      - intro
      - crypto
    redump-policy:
      - strategy: every
        delay: 1d

services:
  chal:
    build: chal
    ports: [80]
