# pathwar/phantomjs:1.9.8
# pathwar/phantomjs:1.9
# pathwar/phantomjs:1
# pathwar/phantomjs:latest

FROM rdpanek/phantomjs:1.9.8
MAINTAINER Pathwar Team <team@pathwar.net> (@pathwar_net)

# Add Pathwar tools
COPY skeleton /pathwar
