// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Achievement = sequelize.define('achievement', {
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    type: {
      type: DataTypes.INTEGER,
    },
    isGlobal: {
      type: DataTypes.INTEGER,
    },
    comment: {
      type: DataTypes.STRING,
    },
    argument: {
      type: DataTypes.STRING,
    },
    challengeValidationId: {
      type: DataTypes.BIGINT,
    },
  }, {
    tableName: 'achievement',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Achievement.associate = (models) => {
    Achievement.belongsTo(models.user, {
      foreignKey: {
        name: 'authorIdKey',
        field: 'author_id',
      },
      as: 'author',
    });
    Achievement.belongsTo(models.team, {
      foreignKey: {
        name: 'teamIdKey',
        field: 'team_id',
      },
      as: 'team',
    });
  };

  return Achievement;
};
