// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Agent = sequelize.define('agent', {
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    name: {
      type: DataTypes.STRING,
    },
    hostname: {
      type: DataTypes.STRING,
    },
    os: {
      type: DataTypes.STRING,
    },
    status: {
      type: DataTypes.INTEGER,
    },
    errMsg: {
      type: DataTypes.STRING,
    },
    arch: {
      type: DataTypes.STRING,
    },
    version: {
      type: DataTypes.STRING,
    },
    tags: {
      type: DataTypes.STRING,
    },
    domainSuffix: {
      type: DataTypes.STRING,
    },
    nginxPort: {
      type: DataTypes.INTEGER,
    },
    metadata: {
      type: DataTypes.STRING,
    },
    timesSeen: {
      type: DataTypes.INTEGER,
    },
    timesRegistered: {
      type: DataTypes.INTEGER,
    },
    lastRegistrationAt: {
      type: DataTypes.DATE,
    },
    lastSeenAt: {
      type: DataTypes.DATE,
    },
    authSalt: {
      type: DataTypes.STRING,
    },
    defaultAgent: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'agent',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Agent.associate = (models) => {
    Agent.hasMany(models.challengeInstance, {
      foreignKey: {
        name: 'agentIdKey',
        field: 'agent_id',
      },
      as: 'challengeInstances',
    });
  };

  return Agent;
};
