NAME =	pathwar/apache-php
VERSIONS =	5.6.4 5.6.4-onbuild \
		5.6.4-gd 5.6.4-gd-onbuild \
		5.6.4-mysql 5.6.4-mysql-onbuild \
		5.6.4-mysqli 5.6.4-mysqli-onbuild \
		5.6.4-full 5.6.4-full-onbuild
EXAMPLES =	hackshells php-mysql

-include ../template.mk
