#!/usr/bin/env python3

import os
import base64

passphrase = os.popen("pwinit passphrase 0").read().strip()
encrypted_passphrase = ("FLAG{" + passphrase + "}").encode('utf-8')
instructions = """
Hello!

I don't know how to decode this: '{}'.
""".format(base64.b64encode(encrypted_passphrase)).strip()

with open("/chal/index.txt", "w") as w:
    w.write(instructions)
