# pathwar/python:3.4.2 pathwar/python:3.4 pathwar/python:3 pathwar/python:latest
FROM python:3.4.2
MAINTAINER Pathwar Team <team@pathwar.net> (@pathwar_net)

# Add Pathwar tools
COPY skeleton /pathwar
