# Pathwar API
Official Pathwar REST Api


# Group People
This section describes about the People


## Person [/people/{id}]
This resource represents one particular person identified by its *id*.

+ Model (application/json)

    {
      "name": "m1ch3l",
      "birthdate": "04-02-1942"
    }


### Retrieve Person [GET]
Return the information for the Person

+ Request (application/json)

+ Response 200 (application/json)

    [Person][]


## Organization [/organization/{id}]
This resource represents one particular organization identified by its *id*.

+ Model (application/json)

    {
      "name": "ulteam"
    }

### Retrieve Organization [GET]
Return the information for the Organization

+ Request (application/json)

+ Response 200 (application/json)

    [Organization][]
