# Pathwar API
Official Pathwar REST Api


## Authentication
To be defined


## Media Types
This API uses the json media-type to represent resources states and affordances.

Requests with a message-body are using plain JSON to set or update resource states.


## Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.


# Group People
This section describes about the People


## User [/user/{id}]
This resource represents one particular user identified by its *id*.

+ Model (application/json)

    {
      "name": "m1ch3l",
      "birthdate": "04-02-1942",
      "organization_id": "xxxx-xxxxxx-xxxxxx-xxxx"
    }


### Retrieve User [GET]
Return the information for the User

+ Request (application/json)

+ Response 200 (application/json)

    [User][]


## Organization [/organization/{id}]
This resource represents one particular organization identified by its *id*.

+ Model (application/json)

    {
      "name": "ulteam",
      "members": [
        "xxxx-xxxxxx-xxxxxx-xxxx",
        "xxxx-xxxxxx-xxxxxx-xxxx",
      ]
    }


### Retrieve Organization [GET]
Return the information for the Organization

+ Request (application/json)

+ Response 200 (application/json)

    [Organization][]


# Group Level
This section describes about the Level


## Level [/level/{id}]
This resource represents one particular level identified by its *id*.

+ Model (application/json)

    {
      "name": "pwnland",
      "description": "pwnland is cool",
      "author": "Pathwar Team (@pathwar_net)"
    }


### Retrieve Level [GET]
Return the information for the Level

+ Request (application/json)

+ Response 200 (application/json)

    [Level][]
