#!/usr/bin/env bash

. /pathwar/scripts/functions.sh
sleep 5 # give enough time to MySQL to start
passphrase1=$(get_passphrase 0)
passphrase2=$(get_passphrase 1)
sed -i "s/__PASSPHRASE2__/$passphrase2/" /var/www/html/step2.php
mysql -h $MYSQL_PORT_3306_TCP_ADDR -u root <<EOF
DROP DATABASE IF EXISTS training_sqli;
CREATE DATABASE training_sqli;
GRANT ALL PRIVILEGES ON training_sqli.* to 'training_sqli'@'%';
USE training_sqli;
CREATE TABLE users (id INTEGER AUTO_INCREMENT PRIMARY KEY, username TEXT, password TEXT);
INSERT INTO users (username, password) VALUES ('admin', '$passphrase1');
CREATE TABLE users2 (id INTEGER AUTO_INCREMENT PRIMARY KEY, username TEXT, password TEXT);
INSERT INTO users (username, password) VALUES ('user', 'supersecurepassword');
EOF
