#!/bin/bash

. /pathwar/scripts/functions.sh
pass1=$(get_passphrase 0)
pass2=$(get_passphrase 1)
pass3=$(get_passphrase 2)
pass4=$(get_passphrase 3)
pass5=$(get_passphrase 5)
sed -i -e "s/__PASSPHRASE1__/$pass1/" /var/www/html/post.php;
sed -i -e "s/__PASSPHRASE2__/$pass2/" /var/www/html/step2.php;
sed -i -e "s/__PASSPHRASE3__/$pass3/" /var/www/html/step2.php;
sed -i -e "s/__PASSPHRASE4__/$pass4/" /var/www/html/redir.php;
sed -i -e "s/__PASSPHRASE5__/$pass5/" /var/www/html/step4.php;
