#!/bin/bash

set -e

. /pathwar/scripts/functions.sh

mkdir -p /pathwar/passphrases
passphrases_number=$(cat /pathwar/level.yml | grep 'passphrases:' | cut -d ':' -f2 | sed -E 's/\s+//g')
for i in $(seq 0 $passphrases_number); do
    passphrase=$(head -c 512 /dev/urandom | sha224sum | awk '// { print $1; }')
    echo $passphrase > /pathwar/passphrases/${i}
done

info "Generated ${i} passphrases"

chmod -R 700 /pathwar/passphrases

[ "$PATHWAR_DEBUG" = True ] && ls -la /pathwar/passphrases || true
